require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CajerosController do

  # This should return the minimal set of attributes required to create a valid
  # Cajero. As you add validations to Cajero, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CajerosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cajeros as @cajeros" do
      cajero = Cajero.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cajeros).should eq([cajero])
    end
  end

  describe "GET show" do
    it "assigns the requested cajero as @cajero" do
      cajero = Cajero.create! valid_attributes
      get :show, {:id => cajero.to_param}, valid_session
      assigns(:cajero).should eq(cajero)
    end
  end

  describe "GET new" do
    it "assigns a new cajero as @cajero" do
      get :new, {}, valid_session
      assigns(:cajero).should be_a_new(Cajero)
    end
  end

  describe "GET edit" do
    it "assigns the requested cajero as @cajero" do
      cajero = Cajero.create! valid_attributes
      get :edit, {:id => cajero.to_param}, valid_session
      assigns(:cajero).should eq(cajero)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cajero" do
        expect {
          post :create, {:cajero => valid_attributes}, valid_session
        }.to change(Cajero, :count).by(1)
      end

      it "assigns a newly created cajero as @cajero" do
        post :create, {:cajero => valid_attributes}, valid_session
        assigns(:cajero).should be_a(Cajero)
        assigns(:cajero).should be_persisted
      end

      it "redirects to the created cajero" do
        post :create, {:cajero => valid_attributes}, valid_session
        response.should redirect_to(Cajero.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cajero as @cajero" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cajero.any_instance.stub(:save).and_return(false)
        post :create, {:cajero => { "nombre" => "invalid value" }}, valid_session
        assigns(:cajero).should be_a_new(Cajero)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cajero.any_instance.stub(:save).and_return(false)
        post :create, {:cajero => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cajero" do
        cajero = Cajero.create! valid_attributes
        # Assuming there are no other cajeros in the database, this
        # specifies that the Cajero created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cajero.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => cajero.to_param, :cajero => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested cajero as @cajero" do
        cajero = Cajero.create! valid_attributes
        put :update, {:id => cajero.to_param, :cajero => valid_attributes}, valid_session
        assigns(:cajero).should eq(cajero)
      end

      it "redirects to the cajero" do
        cajero = Cajero.create! valid_attributes
        put :update, {:id => cajero.to_param, :cajero => valid_attributes}, valid_session
        response.should redirect_to(cajero)
      end
    end

    describe "with invalid params" do
      it "assigns the cajero as @cajero" do
        cajero = Cajero.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cajero.any_instance.stub(:save).and_return(false)
        put :update, {:id => cajero.to_param, :cajero => { "nombre" => "invalid value" }}, valid_session
        assigns(:cajero).should eq(cajero)
      end

      it "re-renders the 'edit' template" do
        cajero = Cajero.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cajero.any_instance.stub(:save).and_return(false)
        put :update, {:id => cajero.to_param, :cajero => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cajero" do
      cajero = Cajero.create! valid_attributes
      expect {
        delete :destroy, {:id => cajero.to_param}, valid_session
      }.to change(Cajero, :count).by(-1)
    end

    it "redirects to the cajeros list" do
      cajero = Cajero.create! valid_attributes
      delete :destroy, {:id => cajero.to_param}, valid_session
      response.should redirect_to(cajeros_url)
    end
  end

end
